---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/OlhaLesk/concourse_input_output.git
      branch: master

jobs:
  - name: job-pass-files
    public: true
    plan:
      - get: resource-tutorial
      - task: create-some-files
        file: resource-tutorial/create.yml
        
      - task: show-some-files
        file: resource-tutorial/show.yml
