---
resources:
  - name: git_repo
    type: git
    source:
      uri: https://github.com/OlhaLesk/concourse_input_output.git
      branch: master

jobs:
  - name: job-pass-files
    public: true
    plan:
      - get: git-repo
        version: every
        trigger: true
      - task: create-some-files
        file: git-repo/create.yml
        
      - task: show-some-files
        file: git-repo/show.yml
